using System.Collections.Immutable;
using System.Text;
using SingletonDI.Generator.Helpers;
using SingletonDI.Generator.Models;

namespace SingletonDI.Generator.Emitters;

/// <summary>
/// Emits partial classes for consumers with properties for singleton access.
/// </summary>
internal static class ConsumerEmitter
{
    /// <summary>
    /// Generates source code for all consumers.
    /// Returns a dictionary mapping file names to source content.
    /// </summary>
    public static ImmutableDictionary<string, string> Generate(
        List<ConsumerModel> consumers,
        ImmutableDictionary<string, string> propertyNames,
        ImmutableDictionary<string, string?> customPropertyNames)
    {
        if (consumers.Count == 0)
        {
            return ImmutableDictionary<string, string>.Empty;
        }

        var validConsumers = consumers;

        var result = ImmutableDictionary.CreateBuilder<string, string>();

        foreach (var consumer in validConsumers)
        {
            var source = GenerateConsumerClass(consumer, propertyNames, customPropertyNames);
            var fileName = $"{consumer.ShortName}.g.cs";
            result[fileName] = source;
        }

        return result.ToImmutable();
    }

    private static string GenerateConsumerClass(
        ConsumerModel consumer,
        ImmutableDictionary<string, string> propertyNames,
        ImmutableDictionary<string, string?> customPropertyNames)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        // Generate namespace if present
        if (!string.IsNullOrEmpty(consumer.Namespace) && consumer.Namespace != "<global namespace>")
        {
            var namespaceName = consumer.Namespace;
            if (namespaceName.StartsWith("global::"))
            {
                namespaceName = namespaceName.Substring("global::".Length);
            }

            sb.AppendLine($"namespace {namespaceName}");
            sb.AppendLine("{");
        }

        // Generate partial class
        sb.AppendLine($"    partial class {consumer.ShortName}");
        sb.AppendLine("    {");

        // Generate properties for each dependency
        foreach (var dep in consumer.Dependencies)
        {
            if (!propertyNames.TryGetValue(dep, out var containerPropertyName))
            {
                continue; // Provider not found
            }

            // Add global:: prefix for proper type resolution
            var formattedType = "global::" + PropertyNameResolver.FormatTypeName(dep);

            // Determine the property name for consumer
            string consumerPropertyName;
            if (customPropertyNames.TryGetValue(dep, out var customName) && !string.IsNullOrEmpty(customName))
            {
                // Use custom property name from attribute
                consumerPropertyName = customName!;
            }
            else
            {
                // Use default: ContainerPropertyName + "Instance" suffix
                consumerPropertyName = containerPropertyName + "Instance";
            }

            sb.AppendLine($"        /// <summary>");
            sb.AppendLine($"        /// Gets the singleton instance of {formattedType}.");
            sb.AppendLine($"        /// </summary>");
            sb.AppendLine($"        protected {formattedType} {consumerPropertyName}");
            sb.AppendLine("        {");
            sb.AppendLine("            get");
            sb.AppendLine("            {");
            sb.AppendLine($"                return global::DependencyManager.Generated.Internal.SingletonContainer.{containerPropertyName};");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        sb.AppendLine("    }");

        // Close namespace if present
        if (!string.IsNullOrEmpty(consumer.Namespace) && consumer.Namespace != "<global namespace>")
        {
            sb.AppendLine("}");
        }

        return sb.ToString();
    }
}
