using System.Collections.Immutable;
using System.Security.Cryptography;
using System.Text;
using SingletonDI.Generator.Helpers;
using SingletonDI.Generator.Models;

namespace SingletonDI.Generator.Emitters;

internal static class ConsumerEmitter
{
    public static ImmutableDictionary<string, string> Generate(List<ConsumerModel> consumers)
    {
        return Generate(
            consumers,
            ImmutableDictionary<ServiceTypeIdentity, string>.Empty,
            ImmutableDictionary<ServiceTypeIdentity, string?>.Empty);
    }

    public static ImmutableDictionary<string, string> Generate(
        List<ConsumerModel> consumers,
        ImmutableDictionary<string, string> propertyNames,
        ImmutableDictionary<string, string?> customPropertyNames)
    {
        if (consumers.Count == 0)
        {
            return ImmutableDictionary<string, string>.Empty;
        }

        var result = ImmutableDictionary.CreateBuilder<string, string>();
        var usedHintNames = new HashSet<string>(StringComparer.Ordinal);
        foreach (var consumer in consumers)
        {
            var names = PropertyNameResolver.ResolveConsumerPropertyNames(
                consumer.Dependencies,
                propertyNames,
                customPropertyNames,
                out _);
            result.Add(
                CreateHintName(consumer.FullyQualifiedName, usedHintNames),
                GenerateConsumerClass(
                    consumer,
                    dependency => names.TryGetValue(dependency.FullyQualifiedName, out var name)
                        ? name
                        : null));
        }

        return result.ToImmutable();
    }

    public static ImmutableDictionary<string, string> Generate(
        List<ConsumerModel> consumers,
        ImmutableDictionary<ServiceTypeIdentity, string> propertyNames,
        ImmutableDictionary<ServiceTypeIdentity, string?> customPropertyNames)
    {
        if (consumers.Count == 0)
        {
            return ImmutableDictionary<string, string>.Empty;
        }

        var result = ImmutableDictionary.CreateBuilder<string, string>();
        var usedHintNames = new HashSet<string>(StringComparer.Ordinal);
        foreach (var consumer in consumers)
        {
            var names = PropertyNameResolver.ResolveConsumerPropertyNamesByIdentity(
                consumer.Dependencies,
                propertyNames,
                customPropertyNames,
                out _);
            result.Add(
                CreateHintName(consumer.FullyQualifiedName, usedHintNames),
                GenerateConsumerClass(
                    consumer,
                    dependency =>
                    {
                        var identity = dependency.Identity is { } dependencyIdentity &&
                                       !string.IsNullOrEmpty(dependencyIdentity.FullyQualifiedName)
                            ? dependencyIdentity
                            : new ServiceTypeIdentity(dependency.FullyQualifiedName, string.Empty);
                        return names.TryGetValue(identity, out var name)
                            ? name
                            : null;
                    }));
        }

        return result.ToImmutable();
    }

    private static string GenerateConsumerClass(
        ConsumerModel consumer,
        Func<ServiceReferenceModel, string?> resolvePropertyName)
    {
        var shape = consumer.Shape;
        var source = new StringBuilder();
        source.AppendLine("// <auto-generated/>");

        var indentLevel = 0;
        var hasNamespace = !string.IsNullOrEmpty(shape.Namespace);
        if (shape.IsFileScoped)
        {
            if (hasNamespace)
            {
                source.AppendLine($"namespace {shape.Namespace};");
            }

            source.AppendLine();
        }
        else
        {
            source.AppendLine("#nullable enable");
            source.AppendLine();
            if (hasNamespace)
            {
                source.AppendLine($"namespace {shape.Namespace}");
                source.AppendLine("{");
                indentLevel++;
            }
        }

        foreach (var containingType in shape.ContainingTypes)
        {
            AppendTypeDeclaration(source, containingType, indentLevel);
            indentLevel++;
        }

        AppendTypeDeclaration(
            source,
            new ConsumerContainingTypeShape(
                shape.Name,
                shape.DeclarationKind,
                shape.Arity,
                shape.TypeParameters,
                shape.TypeParameterList,
                shape.ConstraintClauses,
                shape.IsPartial),
            indentLevel);
        indentLevel++;

        foreach (var dependency in consumer.Dependencies)
        {
            var propertyName = resolvePropertyName(dependency);
            if (propertyName is null ||
                consumer.ExistingMemberNames.Contains(propertyName))
            {
                continue;
            }

            var propertyAccessibility = GetPropertyAccessibility(shape, dependency);
            var dependencyType = ToGlobalTypeName(dependency.FullyQualifiedName);
            source.AppendLine($"{Indent(indentLevel)}/// <summary>");
            source.AppendLine($"{Indent(indentLevel)}/// Gets the singleton instance of {dependencyType}.");
            source.AppendLine($"{Indent(indentLevel)}/// </summary>");
            source.AppendLine($"{Indent(indentLevel)}{propertyAccessibility} static {dependencyType} {propertyName}");
            source.AppendLine(Indent(indentLevel) + "{");
            source.AppendLine($"{Indent(indentLevel + 1)}get");
            source.AppendLine(Indent(indentLevel + 1) + "{");
            source.AppendLine(
                $"{Indent(indentLevel + 2)}return global::SingletonDI.Generated.__SingletonDIHost__.Resolve<{dependencyType}>();");
            source.AppendLine(Indent(indentLevel + 1) + "}");
            source.AppendLine(Indent(indentLevel) + "}");
            source.AppendLine();
        }

        var closingIndentLevel = hasNamespace && !shape.IsFileScoped ? 1 : 0;
        for (var level = indentLevel - 1; level >= closingIndentLevel; level--)
        {
            source.AppendLine(Indent(level) + "}");
        }

        if (hasNamespace && !shape.IsFileScoped)
        {
            source.AppendLine("}");
        }

        return source.ToString();
    }

    private static void AppendTypeDeclaration(
        StringBuilder source,
        ConsumerContainingTypeShape shape,
        int indentLevel)
    {
        source.AppendLine(
            $"{Indent(indentLevel)}partial {GetDeclarationKeyword(shape.DeclarationKind)} {shape.Name}{shape.TypeParameterList}");
        if (!string.IsNullOrWhiteSpace(shape.ConstraintClauses))
        {
            foreach (var line in shape.ConstraintClauses.Split(
                         ['\r', '\n'],
                         StringSplitOptions.RemoveEmptyEntries))
            {
                source.AppendLine($"{Indent(indentLevel + 1)}{line.Trim()}");
            }
        }

        source.AppendLine(Indent(indentLevel) + "{");
    }

    private static string GetDeclarationKeyword(ConsumerDeclarationKind kind)
    {
        return kind switch
        {
            ConsumerDeclarationKind.Struct => "struct",
            ConsumerDeclarationKind.RecordClass => "record class",
            ConsumerDeclarationKind.RecordStruct => "record struct",
            _ => "class",
        };
    }

    private static string GetPropertyAccessibility(
        ConsumerDeclarationShape shape,
        ServiceReferenceModel dependency)
    {
        return shape.DeclarationKind is ConsumerDeclarationKind.Struct or ConsumerDeclarationKind.RecordStruct ||
               shape.IsSealed ||
               !dependency.CanUseProtectedProperty
            ? "private"
            : "protected";
    }

    private static string CreateHintName(string fullyQualifiedName, ISet<string> usedHintNames)
    {
        var identity = fullyQualifiedName.StartsWith("global::", StringComparison.Ordinal)
            ? fullyQualifiedName.Substring("global::".Length)
            : fullyQualifiedName;
        var sanitized = SanitizeHintName(identity);
        if (usedHintNames.Add(sanitized + ".g.cs"))
        {
            return sanitized + ".g.cs";
        }

        using var sha256 = SHA256.Create();
        var hash = BitConverter.ToString(sha256.ComputeHash(Encoding.UTF8.GetBytes(identity)))
            .Replace("-", string.Empty)
            .Substring(0, 8)
            .ToLowerInvariant();
        var candidate = $"{sanitized}_{hash}.g.cs";
        var suffix = 2;
        while (!usedHintNames.Add(candidate))
        {
            candidate = $"{sanitized}_{hash}_{suffix}.g.cs";
            suffix++;
        }

        return candidate;
    }

    private static string SanitizeHintName(string identity)
    {
        var characters = identity
            .Select(character =>
                character is >= 'a' and <= 'z' or >= 'A' and <= 'Z' or >= '0' and <= '9' or '_'
                    ? character
                    : '_')
            .ToArray();
        if (characters.Length == 0)
        {
            return "Consumer";
        }

        if (characters[0] is >= '0' and <= '9')
        {
            return "_" + new string(characters);
        }

        return new string(characters);
    }

    private static string Indent(int level)
    {
        return new string(' ', level * 4);
    }

    private static string ToGlobalTypeName(string fullyQualifiedName)
    {
        return fullyQualifiedName.StartsWith("global::", StringComparison.Ordinal)
            ? fullyQualifiedName
            : $"global::{fullyQualifiedName}";
    }
}
