using System.Collections.Immutable;
using System.Text;
using SingletonDI.Generator.Helpers;
using SingletonDI.Generator.Models;

namespace SingletonDI.Generator.Emitters;

/// <summary>
/// Emits the SingletonContainer class with async parallel initialization support.
/// </summary>
internal static class ContainerEmitter
{
    private const string Namespace = "DependencyManager.Generated.Internal";

    /// <summary>
    /// Generates the SingletonContainer class source code.
    /// </summary>
    public static string Generate(
        ImmutableArray<ProviderModel> providers,
        List<List<ProviderModel>> levels,
        ImmutableDictionary<string, string> propertyNames)
    {
        if (providers.IsEmpty)
        {
            return string.Empty;
        }

        // Convert to list
        var validProviders = providers.ToList();

        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {Namespace}");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Singleton container generated by SingletonDI.");
        sb.AppendLine("    /// Must be initialized by calling SingletonInitializer.InitializeAsync().");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    internal static partial class SingletonContainer");
        sb.AppendLine("    {");

        // Generate fields
        sb.AppendLine("        private static volatile bool _isInitialized;");
        sb.AppendLine("        private static readonly object _lock = new object();");
        sb.AppendLine("        private static global::System.Threading.Tasks.Task? _initializationTask;");
        sb.AppendLine();

        // Generate singleton fields
        foreach (var provider in validProviders)
        {
            var fqn = provider.FullyQualifiedName;
            var formattedType = PropertyNameResolver.FormatTypeName(fqn);
            var fieldName = propertyNames.TryGetValue(fqn, out var name) ? name : provider.ShortName;
            sb.AppendLine($"        private static {formattedType}? _{fieldName};");
        }

        sb.AppendLine();

        // Generate public properties with null check
        foreach (var provider in validProviders)
        {
            var fqn = provider.FullyQualifiedName;
            var formattedType = PropertyNameResolver.FormatTypeName(fqn);
            var fieldName = propertyNames.TryGetValue(fqn, out var name) ? name : provider.ShortName;
            sb.AppendLine($"        public static {formattedType} {fieldName} => _{fieldName} ?? ExceptionHelper.ThrowNotInitialized<{formattedType}>();");
        }

        sb.AppendLine();
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// Initializes all singletons asynchronously with parallel level processing.");
        sb.AppendLine("        /// Thread-safe: uses task caching pattern to ensure single initialization.");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public static global::System.Threading.Tasks.Task InitializeAsync()");
        sb.AppendLine("        {");
        sb.AppendLine("            if (_isInitialized) return global::System.Threading.Tasks.Task.CompletedTask;");
        sb.AppendLine();
        sb.AppendLine("            lock (_lock)");
        sb.AppendLine("            {");
        sb.AppendLine("                if (_isInitialized) return global::System.Threading.Tasks.Task.CompletedTask;");
        sb.AppendLine();
        sb.AppendLine("                // If task is not created yet, create it once");
        sb.AppendLine("                if (_initializationTask == null)");
        sb.AppendLine("                {");
        sb.AppendLine("                    _initializationTask = InitializeInternalAsync();");
        sb.AppendLine("                }");
        sb.AppendLine();
        sb.AppendLine("                return _initializationTask;");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// Internal initialization logic. Called once via task caching pattern.");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        private static async global::System.Threading.Tasks.Task InitializeInternalAsync()");
        sb.AppendLine("        {");
        sb.AppendLine("            try");
        sb.AppendLine("            {");

        // Generate initialization code by levels
        for (int levelIndex = 0; levelIndex < levels.Count; levelIndex++)
        {
            var level = levels[levelIndex];
            sb.AppendLine($"                // Level {levelIndex}");

            // Create instances for this level
            foreach (var provider in level)
            {
                var fqn = provider.FullyQualifiedName;
                var formattedType = PropertyNameResolver.FormatTypeName(fqn);
                var fieldName = propertyNames.TryGetValue(fqn, out var name) ? name : provider.ShortName;

                // Dependencies are injected via generated properties, not constructor
                sb.AppendLine($"                _{fieldName} = new {formattedType}();");
            }

            // Generate parallel initialization for this level (only for providers with InitializeAsync)
            var asyncProviders = level.Where(p => p.HasInitializeAsyncMethod).ToList();
            if (asyncProviders.Count > 0)
            {
                sb.AppendLine();

                if (asyncProviders.Count > 1)
                {
                    // Multiple async providers - run in parallel
                    sb.AppendLine("                await global::System.Threading.Tasks.Task.WhenAll(");
                    for (int i = 0; i < asyncProviders.Count; i++)
                    {
                        var provider = asyncProviders[i];
                        var fqn = provider.FullyQualifiedName;
                        var fieldName = propertyNames.TryGetValue(fqn, out var name) ? name : provider.ShortName;
                        var comma = i < asyncProviders.Count - 1 ? "," : "";
                        sb.AppendLine($"                    _{fieldName}!.InitializeAsync(){comma}");
                    }
                    sb.AppendLine("                );");
                }
                else
                {
                    // Single async provider - direct await
                    var provider = asyncProviders[0];
                    var fqn = provider.FullyQualifiedName;
                    var fieldName = propertyNames.TryGetValue(fqn, out var name) ? name : provider.ShortName;
                    sb.AppendLine($"                await _{fieldName}!.InitializeAsync();");
                }
            }

            sb.AppendLine();
        }

        // Set initialized flag AFTER successful completion
        sb.AppendLine("                // Set initialized flag after successful completion");
        sb.AppendLine("                _isInitialized = true;");
        sb.AppendLine("            }");
        sb.AppendLine("            catch");
        sb.AppendLine("            {");
        sb.AppendLine("                // Reset task on error to allow retry");
        sb.AppendLine("                lock (_lock)");
        sb.AppendLine("                {");
        sb.AppendLine("                    _initializationTask = null;");
        sb.AppendLine("                }");
        sb.AppendLine("                throw;");
        sb.AppendLine("            }");
        sb.AppendLine("        }");

        sb.AppendLine();
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// Throws if container is not initialized.");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        internal static void ThrowIfNotInitialized()");
        sb.AppendLine("        {");
        sb.AppendLine("            if (!_isInitialized)");
        sb.AppendLine("                ExceptionHelper.ThrowContainerNotInitialized();");
        sb.AppendLine("        }");

        // Generate Dispose method if any provider is disposable
        var disposableProviders = validProviders.Where(p => p.IsDisposable).ToList();
        if (disposableProviders.Count > 0)
        {
            sb.AppendLine();
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// Disposes all disposable singleton instances.");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        internal static void Dispose()");
            sb.AppendLine("        {");
            sb.AppendLine("            lock (_lock)");
            sb.AppendLine("            {");

            // Dispose in reverse order
            foreach (var provider in disposableProviders.AsEnumerable().Reverse())
            {
                var fieldName = propertyNames.TryGetValue(provider.FullyQualifiedName, out var name) ? name : provider.ShortName;
                sb.AppendLine($"                if (_{fieldName} is global::System.IDisposable disposable)");
                sb.AppendLine($"                    disposable.Dispose();");
            }

            sb.AppendLine("                _isInitialized = false;");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    /// Builds constructor arguments string for a provider.
    /// </summary>
    private static string BuildConstructorArgs(ProviderModel provider, ImmutableDictionary<string, string> propertyNames)
    {
        if (provider.Dependencies.IsEmpty)
        {
            return string.Empty;
        }

        var args = new List<string>();
        foreach (var dep in provider.Dependencies)
        {
            var fieldName = propertyNames.TryGetValue(dep, out var name) ? name : dep.Split('.').Last();
            args.Add($"_{fieldName}");
        }

        return string.Join(", ", args);
    }
}
