using System.Collections.Immutable;
using System.Text;
using SingletonDI.Generator.Helpers;
using SingletonDI.Generator.Models;

namespace SingletonDI.Generator.Emitters;

/// <summary>
/// Emits the __SingletonDIContainer__ class with async parallel initialization support.
/// </summary>
internal static class ContainerEmitter
{
    /// <summary>
    /// Generates the __SingletonDIContainer__ class source code.
    /// </summary>
    public static string Generate(
        ImmutableArray<ProviderModel> providers,
        List<List<ProviderModel>> levels,
        ImmutableDictionary<string, string> propertyNames)
    {
        if (providers.IsEmpty)
        {
            return string.Empty;
        }

        // Convert to list
        var validProviders = providers.ToList();

        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System.ComponentModel;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine();
        sb.AppendLine($"namespace __SDI.Generated.Internal__");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Singleton container generated by SingletonDI.");
        sb.AppendLine("    /// Must be initialized by calling SingletonDIInitializer.InitializeAsync().");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    [EditorBrowsable(EditorBrowsableState.Never)]");
        sb.AppendLine("    [CompilerGenerated]");
        sb.AppendLine("    internal static partial class __SingletonDIContainer__");
        sb.AppendLine("    {");

        // Generate fields
        sb.AppendLine("        private static volatile bool _isInitialized;");
        sb.AppendLine("        private static readonly object _lock = new object();");
        sb.AppendLine("        private static global::System.Threading.Tasks.Task? _initializationTask;");
        sb.AppendLine();

        // Generate singleton fields
        foreach (var provider in validProviders)
        {
            var fqn = provider.FullyQualifiedName;
            var formattedType = PropertyNameResolver.FormatTypeName(fqn);
            var fieldName = propertyNames.TryGetValue(fqn, out var name) ? name : provider.ShortName;
            sb.AppendLine($"        private static {formattedType}? _{fieldName};");
        }

        sb.AppendLine();

        // Generate public properties with null check
        foreach (var provider in validProviders)
        {
            var fqn = provider.FullyQualifiedName;
            var formattedType = PropertyNameResolver.FormatTypeName(fqn);
            var fieldName = propertyNames.TryGetValue(fqn, out var name) ? name : provider.ShortName;
            sb.AppendLine($"        public static {formattedType} {fieldName} => _{fieldName} ?? __ExceptionHelper__.ThrowNotInitialized<{formattedType}>();");
        }

        sb.AppendLine();
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// Initializes all singletons asynchronously with parallel level processing.");
        sb.AppendLine("        /// Thread-safe: uses task caching pattern to ensure single initialization.");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public static global::System.Threading.Tasks.Task InitializeAsync()");
        sb.AppendLine("        {");
        sb.AppendLine("            if (_isInitialized) return global::System.Threading.Tasks.Task.CompletedTask;");
        sb.AppendLine();
        sb.AppendLine("            lock (_lock)");
        sb.AppendLine("            {");
        sb.AppendLine("                if (_isInitialized) return global::System.Threading.Tasks.Task.CompletedTask;");
        sb.AppendLine();
        sb.AppendLine("                // If task is not created yet, create it once");
        sb.AppendLine("                if (_initializationTask == null)");
        sb.AppendLine("                {");
        sb.AppendLine("                    _initializationTask = InitializeInternalAsync();");
        sb.AppendLine("                }");
        sb.AppendLine();
        sb.AppendLine("                return _initializationTask;");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// Internal initialization logic. Called once via task caching pattern.");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        private static async global::System.Threading.Tasks.Task InitializeInternalAsync()");
        sb.AppendLine("        {");
        sb.AppendLine("            try");
        sb.AppendLine("            {");

        // Generate initialization code by levels
        for (var levelIndex = 0; levelIndex < levels.Count; levelIndex++)
        {
            var level = levels[levelIndex];
            sb.AppendLine($"                // Level {levelIndex}");

            // Create instances for this level
            foreach (var provider in level)
            {
                var fqn = provider.FullyQualifiedName;
                var formattedType = PropertyNameResolver.FormatTypeName(fqn);
                var fieldName = propertyNames.TryGetValue(fqn, out var name) ? name : provider.ShortName;

                // Dependencies are injected via generated properties, not constructor
                sb.AppendLine($"                _{fieldName} = new {formattedType}();");
            }

            // Generate parallel initialization for this level (only for providers with InitializeAsync)
            var asyncProviders = level.Where(p => p.HasInitializeAsyncMethod).ToList();
            if (asyncProviders.Count > 0)
            {
                sb.AppendLine();

                if (asyncProviders.Count > 1)
                {
                    // Multiple async providers - run in parallel
                    sb.AppendLine("                await global::System.Threading.Tasks.Task.WhenAll(");
                    for (var i = 0; i < asyncProviders.Count; i++)
                    {
                        var provider = asyncProviders[i];
                        var fqn = provider.FullyQualifiedName;
                        var fieldName = propertyNames.TryGetValue(fqn, out var name) ? name : provider.ShortName;
                        var comma = i < asyncProviders.Count - 1 ? "," : "";
                        sb.AppendLine($"                    _{fieldName}!.InitializeAsync(){comma}");
                    }
                    sb.AppendLine("                ).ConfigureAwait(false);");
                }
                else
                {
                    // Single async provider - direct await
                    var provider = asyncProviders[0];
                    var fqn = provider.FullyQualifiedName;
                    var fieldName = propertyNames.TryGetValue(fqn, out var name) ? name : provider.ShortName;
                    sb.AppendLine($"                await _{fieldName}!.InitializeAsync().ConfigureAwait(false);");
                }
            }

            sb.AppendLine();
        }

        // Set initialized flag AFTER successful completion
        sb.AppendLine("                // Set initialized flag after successful completion");
        sb.AppendLine("                _isInitialized = true;");
        sb.AppendLine("            }");
        sb.AppendLine("            catch");
        sb.AppendLine("            {");
        sb.AppendLine("                // Reset task on error to allow retry");
        sb.AppendLine("                lock (_lock)");
        sb.AppendLine("                {");
        sb.AppendLine("                    _initializationTask = null;");
        sb.AppendLine("                }");
        sb.AppendLine("                throw;");
        sb.AppendLine("            }");
        sb.AppendLine("        }");

        sb.AppendLine();
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// Throws if container is not initialized.");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        internal static void ThrowIfNotInitialized()");
        sb.AppendLine("        {");
        sb.AppendLine("            if (!_isInitialized)");
        sb.AppendLine("                __ExceptionHelper__.ThrowContainerNotInitialized();");
        sb.AppendLine("        }");

        // Generate DisposeAsync method (always, even if no disposable providers)
        var disposableProviders = validProviders.Where(p => p.IsDisposable || p.IsAsyncDisposable).ToList();

        sb.AppendLine();
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// Disposes all disposable singleton instances asynchronously.");
        sb.AppendLine("        /// Instances are disposed in reverse dependency order (from dependents to dependencies).");
        sb.AppendLine("        /// Instances at the same level are disposed in parallel.");
        sb.AppendLine("        /// Prefers IAsyncDisposable.DisposeAsync over IDisposable.Dispose when both are implemented.");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public static async global::System.Threading.Tasks.ValueTask DisposeAsync()");
        sb.AppendLine("        {");
        sb.AppendLine("            if (!_isInitialized) return;");
        sb.AppendLine();
        sb.AppendLine("            await DisposeInternalAsync().ConfigureAwait(false);");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// Internal dispose logic. Disposes instances level by level in reverse order.");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        private static async global::System.Threading.Tasks.ValueTask DisposeInternalAsync()");
        sb.AppendLine("        {");
        sb.AppendLine("            try");
        sb.AppendLine("            {");

        // Dispose levels in reverse order
        for (var levelIndex = levels.Count - 1; levelIndex >= 0; levelIndex--)
        {
            var level = levels[levelIndex];
            var levelDisposableProviders = level.Where(p => p.IsDisposable || p.IsAsyncDisposable).ToList();

            if (levelDisposableProviders.Count == 0)
            {
                continue;
            }

            sb.AppendLine($"                // Level {levelIndex} (reverse order)");

            if (levelDisposableProviders.Count > 1)
            {
                // Multiple disposable providers at this level - run in parallel
                sb.AppendLine("                await global::System.Threading.Tasks.Task.WhenAll(");

                for (var i = 0; i < levelDisposableProviders.Count; i++)
                {
                    var provider = levelDisposableProviders[i];
                    var fqn = provider.FullyQualifiedName;
                    var fieldName = propertyNames.TryGetValue(fqn, out var name) ? name : provider.ShortName;
                    var comma = i < levelDisposableProviders.Count - 1 ? "," : "";

                    if (provider.IsAsyncDisposable)
                    {
                        // Prefer IAsyncDisposable
                        sb.AppendLine($"                    (_{fieldName} is global::System.IAsyncDisposable asyncDisposable{levelIndex}_{i}");
                        sb.AppendLine($"                        ? asyncDisposable{levelIndex}_{i}.DisposeAsync().AsTask()");
                        sb.AppendLine($"                        : (_{fieldName} is global::System.IDisposable disposable{levelIndex}_{i}");
                        sb.AppendLine($"                            ? global::System.Threading.Tasks.Task.Run(() => disposable{levelIndex}_{i}.Dispose())");
                        sb.AppendLine($"                            : global::System.Threading.Tasks.Task.CompletedTask)){comma}");
                    }
                    else
                    {
                        // Only IDisposable
                        sb.AppendLine($"                    (_{fieldName} is global::System.IDisposable disposable{levelIndex}_{i}");
                        sb.AppendLine($"                        ? global::System.Threading.Tasks.Task.Run(() => disposable{levelIndex}_{i}.Dispose())");
                        sb.AppendLine($"                        : global::System.Threading.Tasks.Task.CompletedTask){comma}");
                    }
                }

                sb.AppendLine("                ).ConfigureAwait(false);");
            }
            else
            {
                // Single disposable provider at this level
                var provider = levelDisposableProviders[0];
                var fqn = provider.FullyQualifiedName;
                var fieldName = propertyNames.TryGetValue(fqn, out var name) ? name : provider.ShortName;

                if (provider.IsAsyncDisposable)
                {
                    sb.AppendLine($"                if (_{fieldName} is global::System.IAsyncDisposable asyncDisposable{levelIndex})");
                    sb.AppendLine($"                    await asyncDisposable{levelIndex}.DisposeAsync().ConfigureAwait(false);");
                    sb.AppendLine($"                else if (_{fieldName} is global::System.IDisposable disposable{levelIndex})");
                    sb.AppendLine($"                    disposable{levelIndex}.Dispose();");
                }
                else
                {
                    sb.AppendLine($"                if (_{fieldName} is global::System.IDisposable disposable{levelIndex})");
                    sb.AppendLine($"                    disposable{levelIndex}.Dispose();");
                }
            }

            sb.AppendLine();
        }

        sb.AppendLine("                // Clear all singleton references");
        foreach (var provider in validProviders)
        {
            var fqn = provider.FullyQualifiedName;
            var fieldName = propertyNames.TryGetValue(fqn, out var name) ? name : provider.ShortName;
            sb.AppendLine($"                _{fieldName} = null;");
        }

        sb.AppendLine();
            sb.AppendLine("                _isInitialized = false;");
            sb.AppendLine("            }");
            sb.AppendLine("            catch");
            sb.AppendLine("            {");
            sb.AppendLine("                // Ensure initialized flag is reset even on error");
            sb.AppendLine("                _isInitialized = false;");
            sb.AppendLine("                throw;");
            sb.AppendLine("            }");
            sb.AppendLine("        }");

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}
