using System.Collections.Immutable;
using System.Text;
using SingletonDI.Generator.Helpers;
using SingletonDI.Generator.Models;

namespace SingletonDI.Generator.Emitters;

/// <summary>
/// Emits the SingletonContainer class with ModuleInitializer and IDisposable support.
/// </summary>
internal static class ContainerEmitter
{
    private const string Namespace = "DependencyManager.Generated.Internal";

    /// <summary>
    /// Generates the SingletonContainer class source code.
    /// </summary>
    public static string Generate(
        ImmutableArray<ProviderModel> providers,
        ImmutableArray<string> topologicalOrder,
        ImmutableDictionary<string, string> propertyNames)
    {
        if (providers.IsEmpty)
        {
            return string.Empty;
        }

        // Convert to list
        var validProviders = providers.ToList();

        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {Namespace}");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Singleton container generated by SingletonDI.");
        sb.AppendLine("    /// Initialized via ModuleInitializer before any user code runs.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    internal static class SingletonContainer");
        sb.AppendLine("    {");

        // Generate fields
        sb.AppendLine("        private static volatile bool _initialized;");
        sb.AppendLine("        private static readonly object _lock = new object();");
        sb.AppendLine();

        // Generate singleton fields
        foreach (var provider in validProviders)
        {
            var fqn = provider.FullyQualifiedName;
            var formattedType = PropertyNameResolver.FormatTypeName(fqn);
            var fieldName = propertyNames.TryGetValue(fqn, out var name) ? name : provider.ShortName;
            sb.AppendLine($"        internal static {formattedType}? {fieldName};");
        }

        sb.AppendLine();
        sb.AppendLine("        [global::System.Runtime.CompilerServices.ModuleInitializer]");
        sb.AppendLine("        internal static void Initialize()");
        sb.AppendLine("        {");
        sb.AppendLine("            lock (_lock)");
        sb.AppendLine("            {");
        sb.AppendLine("                if (_initialized) return;");
        sb.AppendLine();

        // Generate initialization code in topological order
        foreach (var fqn in topologicalOrder)
        {
            var provider = validProviders.First(p => p.FullyQualifiedName == fqn);
            var formattedType = PropertyNameResolver.FormatTypeName(fqn);
            var fieldName = propertyNames.TryGetValue(fqn, out var name) ? name : provider.ShortName;

            // Create instance
            sb.AppendLine($"                {fieldName} = new {formattedType}();");

            // Sync initialization
            if (provider.HasSyncInit)
            {
                sb.AppendLine($"                if ({fieldName} is SingletonDI.Attributes.IInitializeSync sync{fieldName})");
                sb.AppendLine($"                    sync{fieldName}.Initialize();");
            }

            // Async initialization
            if (provider.HasAsyncInit)
            {
                sb.AppendLine($"                if ({fieldName} is SingletonDI.Attributes.IInitializeAsync asyncInit{fieldName})");
                sb.AppendLine("                {");
                sb.AppendLine($"                    var task = asyncInit{fieldName}.InitializeAsync();");
                sb.AppendLine("                    if (!task.IsCompleted)");
                sb.AppendLine("                        task.GetAwaiter().GetResult();");
                sb.AppendLine("                }");
            }
        }

        sb.AppendLine();
        sb.AppendLine("                _initialized = true;");
        sb.AppendLine("            }");
        sb.AppendLine("        }");

        sb.AppendLine();
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// Throws if container is not initialized.");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        internal static void ThrowIfNotInitialized()");
        sb.AppendLine("        {");
        sb.AppendLine("            if (!_initialized)");
        sb.AppendLine("                ExceptionHelper.ThrowContainerNotInitialized();");
        sb.AppendLine("        }");

        // Generate Dispose method if any provider is disposable
        var disposableProviders = validProviders.Where(p => p.IsDisposable).ToList();
        if (disposableProviders.Count > 0)
        {
            sb.AppendLine();
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// Disposes all disposable singleton instances.");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        internal static void Dispose()");
            sb.AppendLine("        {");
            sb.AppendLine("            lock (_lock)");
            sb.AppendLine("            {");

            // Dispose in reverse order
            foreach (var provider in disposableProviders.AsEnumerable().Reverse())
            {
                var fieldName = propertyNames.TryGetValue(provider.FullyQualifiedName, out var name) ? name : provider.ShortName;
                sb.AppendLine($"                if ({fieldName} is global::System.IDisposable disposable)");
                sb.AppendLine($"                    disposable.Dispose();");
            }

            sb.AppendLine("                _initialized = false;");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}
