namespace SingletonDI.Generator.Emitters;

/// <summary>
/// Emits the __ExceptionHelper__ class with [DoesNotReturn] methods for throwing exceptions.
/// </summary>
internal static class ExceptionHelperEmitter
{
    /// <summary>
    /// Generates the __ExceptionHelper__ class source code.
    /// </summary>
    public static string Generate()
    {
        return """
               // <auto-generated/>
               #nullable enable
               using System.ComponentModel;
               using System.Runtime.CompilerServices;

               namespace __SDI.Generated.Internal__
               {
                   /// <summary>
                   /// Helper class for throwing exceptions.
                   /// Methods are marked with [DoesNotReturn] for compiler optimization.
                   /// </summary>
                   [EditorBrowsable(EditorBrowsableState.Never)]
                   [CompilerGenerated]
                   internal static class __ExceptionHelper__
                   {
                       /// <summary>
                       /// Throws InvalidOperationException when the container has not been initialized.
                       /// </summary>
                       [global::System.Diagnostics.CodeAnalysis.DoesNotReturn]
                       internal static void ThrowContainerNotInitialized() =>
                           throw new global::System.InvalidOperationException(
                               "Singleton container has not been initialized. " +
                               "Call SingletonDIInitializer.InitializeAsync() before accessing singletons."
                           );
                       
                       /// <summary>
                       /// Throws InvalidOperationException when a singleton is accessed before initialization.
                       /// </summary>
                       /// <typeparam name="T">The type of the singleton.</typeparam>
                       /// <returns>Never returns, always throws.</returns>
                       [global::System.Diagnostics.CodeAnalysis.DoesNotReturn]
                       internal static T ThrowNotInitialized<T>() =>
                           throw new global::System.InvalidOperationException(
                               $"Singleton of type '{typeof(T).Name}' has not been initialized. " +
                               "Call SingletonDIInitializer.InitializeAsync() before accessing singletons."
                           );
                       
                       /// <summary>
                       /// Throws InvalidOperationException when a singleton is null.
                       /// </summary>
                       /// <param name="typeName">The name of the singleton type.</param>
                       [global::System.Diagnostics.CodeAnalysis.DoesNotReturn]
                       internal static void ThrowSingletonNull(string typeName) =>
                           throw new global::System.InvalidOperationException(
                               $"Singleton '{typeName}' is null. This should not happen."
                           );
                   }
               }
               """;
    }
}
