namespace SingletonDI.Generator.Emitters;

/// <summary>
/// Emits the ExceptionHelper class with [DoesNotReturn] methods for throwing exceptions.
/// </summary>
internal static class ExceptionHelperEmitter
{
    private const string Namespace = "DependencyManager.Generated.Internal";

    /// <summary>
    /// Generates the ExceptionHelper class source code.
    /// </summary>
    public static string Generate()
    {
        return $$"""
                 // <auto-generated/>
                 #nullable enable
                 
                 namespace {{Namespace}}
                 {
                     /// <summary>
                     /// Helper class for throwing exceptions.
                     /// Methods are marked with [DoesNotReturn] for compiler optimization.
                     /// </summary>
                     internal static class ExceptionHelper
                     {
                         /// <summary>
                         /// Throws InvalidOperationException when the container has not been initialized.
                         /// </summary>
                         [global::System.Diagnostics.CodeAnalysis.DoesNotReturn]
                         internal static void ThrowContainerNotInitialized() =>
                             throw new global::System.InvalidOperationException(
                                 "Singleton container has not been initialized. " +
                                 "Call SingletonDIInitializer.InitializeAsync() before accessing singletons."
                             );
                         
                         /// <summary>
                         /// Throws InvalidOperationException when a singleton is accessed before initialization.
                         /// </summary>
                         /// <typeparam name="T">The type of the singleton.</typeparam>
                         /// <returns>Never returns, always throws.</returns>
                         [global::System.Diagnostics.CodeAnalysis.DoesNotReturn]
                         internal static T ThrowNotInitialized<T>() =>
                             throw new global::System.InvalidOperationException(
                                 $"Singleton of type '{typeof(T).Name}' has not been initialized. " +
                                 "Call SingletonDIInitializer.InitializeAsync() before accessing singletons."
                             );
                         
                         /// <summary>
                         /// Throws InvalidOperationException when a singleton is null.
                         /// </summary>
                         /// <param name="typeName">The name of the singleton type.</param>
                         [global::System.Diagnostics.CodeAnalysis.DoesNotReturn]
                         internal static void ThrowSingletonNull(string typeName) =>
                             throw new global::System.InvalidOperationException(
                                 $"Singleton '{typeName}' is null. This should not happen."
                             );
                     }
                 }
                 """;
    }
}
