using System.Text;

namespace SingletonDI.Generator.Emitters;

/// <summary>
/// Emits the ExceptionHelper class with [DoesNotReturn] methods for throwing exceptions.
/// </summary>
internal static class ExceptionHelperEmitter
{
    private const string Namespace = "DependencyManager.Generated.Internal";

    /// <summary>
    /// Generates the ExceptionHelper class source code.
    /// </summary>
    public static string Generate()
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {Namespace}");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Helper class for throwing exceptions.");
        sb.AppendLine("    /// Methods are marked with [DoesNotReturn] for compiler optimization.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    internal static class ExceptionHelper");
        sb.AppendLine("    {");
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// Throws InvalidOperationException when the container has not been initialized.");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        [global::System.Diagnostics.CodeAnalysis.DoesNotReturn]");
        sb.AppendLine("        internal static void ThrowContainerNotInitialized() =>");
        sb.AppendLine("            throw new global::System.InvalidOperationException(");
        sb.AppendLine("                \"Singleton container has not been initialized. \" +");
        sb.AppendLine("                \"Call SingletonInitializer.InitializeAsync() before accessing singletons.\"");
        sb.AppendLine("            );");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// Throws InvalidOperationException when a singleton is accessed before initialization.");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        /// <typeparam name=\"T\">The type of the singleton.</typeparam>");
        sb.AppendLine("        /// <returns>Never returns, always throws.</returns>");
        sb.AppendLine("        [global::System.Diagnostics.CodeAnalysis.DoesNotReturn]");
        sb.AppendLine("        internal static T ThrowNotInitialized<T>() =>");
        sb.AppendLine("            throw new global::System.InvalidOperationException(");
        sb.AppendLine("                $\"Singleton of type '{typeof(T).Name}' has not been initialized. \" +");
        sb.AppendLine("                \"Call SingletonInitializer.InitializeAsync() before accessing singletons.\"");
        sb.AppendLine("            );");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// Throws InvalidOperationException when a singleton is null.");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        /// <param name=\"typeName\">The name of the singleton type.</param>");
        sb.AppendLine("        [global::System.Diagnostics.CodeAnalysis.DoesNotReturn]");
        sb.AppendLine("        internal static void ThrowSingletonNull(string typeName) =>");
        sb.AppendLine("            throw new global::System.InvalidOperationException(");
        sb.AppendLine("                $\"Singleton '{typeName}' is null. This should not happen.\"");
        sb.AppendLine("            );");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}
