namespace SingletonDI.Generator.Emitters;

/// <summary>
/// Emits the __SingletonDILifetime__ class for handling OS shutdown signals.
/// </summary>
internal static class LifetimeEmitter
{
    /// <summary>
    /// Generates the __SingletonDILifetime__ class source code.
    /// </summary>
    public static string Generate()
    {
        return """
               // <auto-generated/>
               #nullable enable
               using System;
               using System.Collections.Generic;
               using System.Runtime.InteropServices;
               using System.Threading.Tasks;
               using System.ComponentModel;
               using System.Runtime.CompilerServices;

               namespace __SDI.Generated.Internal__
               {
                   /// <summary>
                   /// Handles OS shutdown signals and ensures proper disposal of singleton instances.
                   /// Register shutdown handlers at application startup to enable graceful shutdown.
                   /// </summary>
                   [EditorBrowsable(EditorBrowsableState.Never)]
                   [CompilerGenerated]
                   internal sealed class __SingletonDILifetime__ : IDisposable
                   {
                       private static __SingletonDILifetime__? _instance;
                       private static readonly object _lock = new object();
                       
                       private IEnumerable<IDisposable>? _posixRegistrations;
                       private bool _isDisposed;

                       /// <summary>
                       /// Gets the singleton instance of the lifetime manager.
                       /// </summary>
                       public static __SingletonDILifetime__ Instance
                       {
                           get
                           {
                               if (_instance == null)
                               {
                                   lock (_lock)
                                   {
                                       _instance ??= new __SingletonDILifetime__();
                                   }
                               }
                               return _instance;
                           }
                       }

                       private __SingletonDILifetime__()
                       {
                       }

                       /// <summary>
                       /// Registers shutdown handlers for the current platform.
                       /// On Linux/macOS: handles SIGINT, SIGTERM, SIGQUIT via PosixSignalRegistration.
                       /// On Windows: handles ProcessExit and CancelKeyPress.
                       /// </summary>
                       public void RegisterShutdownHandlers()
                       {
                           if (_isDisposed) return;

                           // Platform-specific signal handling
                           if (RuntimeInformation.IsOSPlatform(OSPlatform.Linux) || 
                               RuntimeInformation.IsOSPlatform(OSPlatform.OSX))
                           {
                               RegisterPosixSignals();
                           }

                           // Cross-platform handlers
                           AppDomain.CurrentDomain.ProcessExit += OnProcessExit;
                           Console.CancelKeyPress += OnCancelKeyPress;
                       }

                       [System.Runtime.Versioning.SupportedOSPlatform("linux")]
                       [System.Runtime.Versioning.SupportedOSPlatform("osx")]
                       private void RegisterPosixSignals()
                       {
                           try
                           {
                               _posixRegistrations = new IDisposable[]
                               {
                                   PosixSignalRegistration.Create(PosixSignal.SIGINT, HandlePosixSignal),
                                   PosixSignalRegistration.Create(PosixSignal.SIGTERM, HandlePosixSignal),
                                   PosixSignalRegistration.Create(PosixSignal.SIGQUIT, HandlePosixSignal)
                               };
                           }
                           catch (PlatformNotSupportedException)
                           {
                               // PosixSignalRegistration not supported on this platform
                               _posixRegistrations = null;
                           }
                       }

                       private void HandlePosixSignal(PosixSignalContext context)
                       {
                           context.Cancel = true;
                           _ = ShutdownAsync();
                       }

                       private void OnProcessExit(object? sender, EventArgs e)
                       {
                           _ = ShutdownAsync();
                       }

                       private void OnCancelKeyPress(object? sender, ConsoleCancelEventArgs e)
                       {
                           e.Cancel = true;
                           _ = ShutdownAsync();
                       }

                       /// <summary>
                       /// Performs graceful shutdown by disposing all singleton instances.
                       /// </summary>
                       private async Task ShutdownAsync()
                       {
                           try
                           {
                               await __SingletonDIContainer__.DisposeAsync().ConfigureAwait(false);
                           }
                           catch
                           {
                               // Ignore exceptions during shutdown
                           }
                       }

                       /// <summary>
                       /// Unregisters all shutdown handlers and releases resources.
                       /// </summary>
                       public void Dispose()
                       {
                           if (_isDisposed) return;
                           _isDisposed = true;

                           // Unregister POSIX signals
                           if (_posixRegistrations != null)
                           {
                               foreach (var registration in _posixRegistrations)
                               {
                                   try
                                   {
                                       registration.Dispose();
                                   }
                                   catch
                                   {
                                       // Ignore disposal errors
                                   }
                               }
                               _posixRegistrations = null;
                           }

                           // Unregister cross-platform handlers
                           AppDomain.CurrentDomain.ProcessExit -= OnProcessExit;
                           Console.CancelKeyPress -= OnCancelKeyPress;
                       }
                   }
               }
               """;
    }
}
