namespace SingletonDI.Generator.Emitters;

/// <summary>
/// Emits the SingletonInitializer class that provides public API for initialization.
/// </summary>
internal static class SingletonInitializerEmitter
{
    /// <summary>
    /// Generates the SingletonInitializer class source code.
    /// </summary>
    public static string Generate()
    {
        return """
               // <auto-generated/>
               #nullable enable
               using __SDI.Generated.Internal__;

               namespace SingletonDI.Generated
               {
                   /// <summary>
                   /// Provides public API for initializing and disposing the singleton container.
                   /// Call InitializeAsync() at application startup before accessing any singletons.
                   /// </summary>
                   public static class SingletonDIInitializer
                   {
                       /// <summary>
                       /// Initializes all singleton instances asynchronously.
                       /// Singletons on the same dependency level are initialized in parallel.
                       /// </summary>
                       /// <param name="registerShutdownHandlers">
                       /// When true (default), registers OS shutdown signal handlers for graceful disposal.
                       /// Set to false if you want to manually control disposal timing.
                       /// </param>
                       /// <returns>A task that completes when all singletons are initialized.</returns>
                       public static async global::System.Threading.Tasks.Task InitializeAsync(bool registerShutdownHandlers = true)
                       {
                           await __SDI.Generated.Internal__.__SingletonDIContainer__.InitializeAsync().ConfigureAwait(false);
                           
                           if (registerShutdownHandlers)
                           {
                               RegisterShutdownHandlers();
                           }
                       }

                       /// <summary>
                       /// Registers OS shutdown signal handlers for graceful disposal.
                       /// On Linux/macOS: handles SIGINT, SIGTERM, SIGQUIT.
                       /// On Windows: handles ProcessExit and CancelKeyPress.
                       /// </summary>
                       private static void RegisterShutdownHandlers() =>
                           __SDI.Generated.Internal__.__SingletonDILifetime__.Instance.RegisterShutdownHandlers();

                       /// <summary>
                       /// Disposes all disposable singleton instances asynchronously.
                       /// Instances are disposed in reverse dependency order.
                       /// Instances at the same level are disposed in parallel.
                       /// Prefers IAsyncDisposable.DisposeAsync over IDisposable.Dispose when both are implemented.
                       /// </summary>
                       /// <returns>A task that completes when all disposable instances are disposed.</returns>
                       public static global::System.Threading.Tasks.ValueTask DisposeAsync() =>
                           __SDI.Generated.Internal__.__SingletonDIContainer__.DisposeAsync();
                   }
               }
               """;
    }
}
