using System.Text;

namespace SingletonDI.Generator.Emitters;

/// <summary>
/// Emits the SingletonInitializer class that provides public API for initialization.
/// </summary>
internal static class SingletonInitializerEmitter
{
    private const string Namespace = "DependencyManager.Generated";

    /// <summary>
    /// Generates the SingletonInitializer class source code.
    /// </summary>
    public static string Generate()
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {Namespace}");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Provides public API for initializing the singleton container.");
        sb.AppendLine("    /// Call InitializeAsync() at application startup before accessing any singletons.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static class SingletonInitializer");
        sb.AppendLine("    {");
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// Initializes all singleton instances asynchronously.");
        sb.AppendLine("        /// Singletons on the same dependency level are initialized in parallel.");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        /// <returns>A task that completes when all singletons are initialized.</returns>");
        sb.AppendLine("        public static global::System.Threading.Tasks.Task InitializeAsync() =>");
        sb.AppendLine("            Internal.SingletonContainer.InitializeAsync();");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}
