using System.Collections.Immutable;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using SingletonDI.Generator;
using Xunit;

namespace SingletonDI.Tests;

/// <summary>
/// Tests for property name resolution in SingletonDI.Generator.
/// These tests verify that property names are correctly generated by compiling code
/// that uses the generated properties. If the code compiles successfully, the properties
/// exist with the correct names and types.
/// </summary>
public class PropertyNameResolverTests
{
    #region TC01-TC03: Basic Scenarios

    /// <summary>
    /// TC01: Single provider without conflict.
    /// Expected property name: {ShortName}Instance (e.g., MyServiceInstance)
    /// </summary>
    [Fact]
    public void TC01_SingleProvider_NoConflict_GeneratesShortNameProperty()
    {
        const string SOURCE = """
            using SingletonDI.Attributes;

            namespace MyApp.Services
            {
                [SingletonDIProvide]
                public class MyService
                {
                    public void DoWork() { }
                }

                [SingletonDIConsume(typeof(MyService))]
                public partial class Consumer
                {
                    public void UseService()
                    {
                        MyService service = MyServiceInstance;
                        service.DoWork();
                    }
                }

                public class DerivedConsumer : Consumer
                {
                    public void UseServiceFromDerived()
                    {
                        MyService service = MyServiceInstance;
                        service.DoWork();
                    }
                }
            }
            """;

        var compilationErrors = CompilationErrors(SOURCE);

        Assert.Empty(compilationErrors);
    }

    /// <summary>
    /// TC02: Single provider with custom property name.
    /// Expected property name: {CustomName} (without Instance suffix)
    /// </summary>
    [Fact]
    public void TC02_SingleProvider_WithCustomName_UsesCustomName()
    {
        const string SOURCE = """
            using SingletonDI.Attributes;

            namespace MyApp.Services
            {
                [SingletonDIProvide("CustomService")]
                public class MyService
                {
                    public void DoWork() { }
                }

                [SingletonDIConsume(typeof(MyService))]
                public partial class Consumer
                {
                    public void UseService()
                    {
                        MyService service = CustomService;
                        service.DoWork();
                    }
                }

                public class DerivedConsumer : Consumer
                {
                    public void UseServiceFromDerived()
                    {
                        MyService service = CustomService;
                        service.DoWork();
                    }
                }
            }
            """;

        var compilationErrors = CompilationErrors(SOURCE);

        Assert.Empty(compilationErrors);
    }

    /// <summary>
    /// TC03: Provider in global namespace (no namespace).
    /// Expected property name: {ShortName}Instance (without namespace prefix)
    /// </summary>
    [Fact]
    public void TC03_Provider_InGlobalNamespace_UsesShortName()
    {
        const string SOURCE = """
            using SingletonDI.Attributes;

            [SingletonDIProvide]
            public class GlobalService
            {
                public void DoWork() { }
            }

            namespace MyApp
            {
                [SingletonDIConsume(typeof(GlobalService))]
                public partial class Consumer
                {
                    public void UseService()
                    {
                        GlobalService service = GlobalServiceInstance;
                        service.DoWork();
                    }
                }

                public class DerivedConsumer : Consumer
                {
                    public void UseServiceFromDerived()
                    {
                        GlobalService service = GlobalServiceInstance;
                        service.DoWork();
                    }
                }
            }
            """;

        var compilationErrors = CompilationErrors(SOURCE);

        Assert.Empty(compilationErrors);
    }

    #endregion

    #region TC04-TC06: ShortName Conflicts

    /// <summary>
    /// TC04: Two providers with the same ShortName.
    /// Expected property names: {Namespace}_{ShortName}Instance for both
    /// </summary>
    [Fact]
    public void TC04_TwoProviders_SameShortName_GeneratesNamespacedProperties()
    {
        const string SOURCE = """
            using SingletonDI.Attributes;

            namespace NamespaceA
            {
                [SingletonDIProvide]
                public class Service { }
            }

            namespace NamespaceB
            {
                [SingletonDIProvide]
                public class Service { }
            }

            namespace ConsumerNamespace
            {
                [SingletonDIConsume(typeof(NamespaceA.Service), typeof(NamespaceB.Service))]
                public partial class Consumer
                {
                    public void UseServices()
                    {
                        NamespaceA.Service a = NamespaceA_ServiceInstance;
                        NamespaceB.Service b = NamespaceB_ServiceInstance;
                    }
                }

                public class DerivedConsumer : Consumer
                {
                    public void UseServicesFromDerived()
                    {
                        NamespaceA.Service a = NamespaceA_ServiceInstance;
                        NamespaceB.Service b = NamespaceB_ServiceInstance;
                    }
                }
            }
            """;

        var compilationErrors = CompilationErrors(SOURCE);

        Assert.Empty(compilationErrors);
    }

    /// <summary>
    /// TC05: Three providers with the same ShortName.
    /// Expected property names: {Namespace}_{ShortName}Instance for all three
    /// </summary>
    [Fact]
    public void TC05_ThreeProviders_SameShortName_GeneratesNamespacedProperties()
    {
        const string SOURCE = """
            using SingletonDI.Attributes;

            namespace NamespaceA
            {
                [SingletonDIProvide]
                public class Service { }
            }

            namespace NamespaceB
            {
                [SingletonDIProvide]
                public class Service { }
            }

            namespace NamespaceC
            {
                [SingletonDIProvide]
                public class Service { }
            }

            namespace ConsumerNamespace
            {
                [SingletonDIConsume(typeof(NamespaceA.Service), typeof(NamespaceB.Service), typeof(NamespaceC.Service))]
                public partial class Consumer
                {
                    public void UseServices()
                    {
                        NamespaceA.Service a = NamespaceA_ServiceInstance;
                        NamespaceB.Service b = NamespaceB_ServiceInstance;
                        NamespaceC.Service c = NamespaceC_ServiceInstance;
                    }
                }

                public class DerivedConsumer : Consumer
                {
                    public void UseServicesFromDerived()
                    {
                        NamespaceA.Service a = NamespaceA_ServiceInstance;
                        NamespaceB.Service b = NamespaceB_ServiceInstance;
                        NamespaceC.Service c = NamespaceC_ServiceInstance;
                    }
                }
            }
            """;

        var compilationErrors = CompilationErrors(SOURCE);

        Assert.Empty(compilationErrors);
    }

    /// <summary>
    /// TC06: Nested namespace with conflict.
    /// Expected property names: {Nested_Namespace}_{ShortName}Instance (dots replaced with underscores)
    /// </summary>
    [Fact]
    public void TC06_NestedNamespace_WithConflict_GeneratesCorrectPrefix()
    {
        const string SOURCE = """
            using SingletonDI.Attributes;

            namespace Company.Project.Services
            {
                [SingletonDIProvide]
                public class Repository
                {
                    public string Type => "Services";
                }
            }

            namespace Company.Project.Data
            {
                [SingletonDIProvide]
                public class Repository
                {
                    public string Type => "Data";
                }
            }

            namespace ConsumerNamespace
            {
                [SingletonDIConsume(typeof(Company.Project.Services.Repository), typeof(Company.Project.Data.Repository))]
                public partial class Consumer
                {
                    public void UseRepositories()
                    {
                        Company.Project.Services.Repository servicesRepo = Company_Project_Services_RepositoryInstance;
                        Company.Project.Data.Repository dataRepo = Company_Project_Data_RepositoryInstance;
                    }
                }

                public class DerivedConsumer : Consumer
                {
                    public void UseRepositoriesFromDerived()
                    {
                        Company.Project.Services.Repository servicesRepo = Company_Project_Services_RepositoryInstance;
                        Company.Project.Data.Repository dataRepo = Company_Project_Data_RepositoryInstance;
                    }
                }
            }
            """;

        var compilationErrors = CompilationErrors(SOURCE);

        Assert.Empty(compilationErrors);
    }

    #endregion

    #region TC07-TC09: Mixed Scenarios

    /// <summary>
    /// TC07: Two providers with same ShortName, one with custom name.
    /// Expected: Custom name used as-is, other gets {ShortName}Instance
    /// </summary>
    [Fact]
    public void TC07_TwoProviders_OneWithCustomName_GeneratesCorrectProperties()
    {
        const string SOURCE = """
            using SingletonDI.Attributes;

            namespace NamespaceA
            {
                [SingletonDIProvide("CustomService")]
                public class Service { }
            }

            namespace NamespaceB
            {
                [SingletonDIProvide]
                public class Service { }
            }

            namespace ConsumerNamespace
            {
                [SingletonDIConsume(typeof(NamespaceA.Service), typeof(NamespaceB.Service))]
                public partial class Consumer
                {
                    public void UseServices()
                    {
                        NamespaceA.Service custom = CustomService;
                        NamespaceB.Service regular = ServiceInstance;
                    }
                }

                public class DerivedConsumer : Consumer
                {
                    public void UseServicesFromDerived()
                    {
                        NamespaceA.Service custom = CustomService;
                        NamespaceB.Service regular = ServiceInstance;
                    }
                }
            }
            """;

        var compilationErrors = CompilationErrors(SOURCE);

        Assert.Empty(compilationErrors);
    }

    /// <summary>
    /// TC08: Three providers, two with custom names, one without.
    /// Expected: Custom names used, third gets {ShortName}Instance
    /// </summary>
    [Fact]
    public void TC08_ThreeProviders_TwoWithCustomNames_GeneratesCorrectProperties()
    {
        const string SOURCE = """
            using SingletonDI.Attributes;

            namespace NamespaceX
            {
                [SingletonDIProvide("ProviderX")]
                public class Provider { }
            }

            namespace NamespaceY
            {
                [SingletonDIProvide("ProviderY")]
                public class Provider { }
            }

            namespace NamespaceZ
            {
                [SingletonDIProvide]
                public class Provider { }
            }

            namespace ConsumerNamespace
            {
                [SingletonDIConsume(typeof(NamespaceX.Provider), typeof(NamespaceY.Provider), typeof(NamespaceZ.Provider))]
                public partial class Consumer
                {
                    public void UseProviders()
                    {
                        NamespaceX.Provider x = ProviderX;
                        NamespaceY.Provider y = ProviderY;
                        NamespaceZ.Provider z = ProviderInstance;
                    }
                }

                public class DerivedConsumer : Consumer
                {
                    public void UseProvidersFromDerived()
                    {
                        NamespaceX.Provider x = ProviderX;
                        NamespaceY.Provider y = ProviderY;
                        NamespaceZ.Provider z = ProviderInstance;
                    }
                }
            }
            """;

        var compilationErrors = CompilationErrors(SOURCE);

        Assert.Empty(compilationErrors);
    }

    /// <summary>
    /// TC09: Mixed providers - one without conflict, two with conflict.
    /// Expected: No conflict uses {ShortName}Instance, conflicts use namespace prefix
    /// </summary>
    [Fact]
    public void TC09_MixedProviders_WithAndWithoutConflicts_GeneratesCorrectNames()
    {
        const string SOURCE = """
            using SingletonDI.Attributes;

            namespace NamespaceA
            {
                [SingletonDIProvide]
                public class UniqueService { }
            }

            namespace NamespaceB
            {
                [SingletonDIProvide]
                public class ConflictingService { }
            }

            namespace NamespaceC
            {
                [SingletonDIProvide]
                public class ConflictingService { }
            }

            namespace ConsumerNamespace
            {
                [SingletonDIConsume(typeof(NamespaceA.UniqueService), typeof(NamespaceB.ConflictingService), typeof(NamespaceC.ConflictingService))]
                public partial class Consumer
                {
                    public void UseServices()
                    {
                        NamespaceA.UniqueService unique = UniqueServiceInstance;
                        NamespaceB.ConflictingService b = NamespaceB_ConflictingServiceInstance;
                        NamespaceC.ConflictingService c = NamespaceC_ConflictingServiceInstance;
                    }
                }

                public class DerivedConsumer : Consumer
                {
                    public void UseServicesFromDerived()
                    {
                        NamespaceA.UniqueService unique = UniqueServiceInstance;
                        NamespaceB.ConflictingService b = NamespaceB_ConflictingServiceInstance;
                        NamespaceC.ConflictingService c = NamespaceC_ConflictingServiceInstance;
                    }
                }
            }
            """;

        var compilationErrors = CompilationErrors(SOURCE);

        Assert.Empty(compilationErrors);
    }

    #endregion

    #region TC10-TC12: Edge Cases

    /// <summary>
    /// TC10: Custom name matches another provider's ShortName.
    /// Expected: No conflict - custom name takes precedence
    /// </summary>
    [Fact]
    public void TC10_CustomName_MatchesOtherProviderShortName_NoConflict()
    {
        const string SOURCE = """
            using SingletonDI.Attributes;

            namespace NamespaceA
            {
                [SingletonDIProvide("ServiceB")]
                public class ServiceA { }
            }

            namespace NamespaceB
            {
                [SingletonDIProvide]
                public class ServiceB { }
            }

            namespace ConsumerNamespace
            {
                [SingletonDIConsume(typeof(NamespaceA.ServiceA), typeof(NamespaceB.ServiceB))]
                public partial class Consumer
                {
                    public void UseServices()
                    {
                        // ServiceA uses custom name "ServiceB"
                        NamespaceA.ServiceA a = ServiceB;
                        // ServiceB uses its ShortName with Instance suffix
                        NamespaceB.ServiceB b = ServiceBInstance;
                    }
                }

                public class DerivedConsumer : Consumer
                {
                    public void UseServicesFromDerived()
                    {
                        NamespaceA.ServiceA a = ServiceB;
                        NamespaceB.ServiceB b = ServiceBInstance;
                    }
                }
            }
            """;

        var compilationErrors = CompilationErrors(SOURCE);

        Assert.Empty(compilationErrors);
    }

    /// <summary>
    /// TC12: Provider with nested class.
    /// Expected: Correct property name generation
    /// </summary>
    [Fact]
    public void TC12_Provider_WithNestedClass_GeneratesCorrectName()
    {
        const string SOURCE = """
            using SingletonDI.Attributes;

            namespace MyApp.Services
            {
                public class OuterClass
                {
                    [SingletonDIProvide]
                    public class NestedService
                    {
                        public void DoWork() { }
                    }
                }

                [SingletonDIConsume(typeof(OuterClass.NestedService))]
                public partial class Consumer
                {
                    public void UseService()
                    {
                        OuterClass.NestedService service = NestedServiceInstance;
                        service.DoWork();
                    }
                }

                public class DerivedConsumer : Consumer
                {
                    public void UseServiceFromDerived()
                    {
                        OuterClass.NestedService service = NestedServiceInstance;
                        service.DoWork();
                    }
                }
            }
            """;

        var compilationErrors = CompilationErrors(SOURCE);

        Assert.Empty(compilationErrors);
    }

    #endregion

    #region TC13-TC15: Inheritance Chain Tests

    /// <summary>
    /// TC13: Inheritance chain - Class A with SingletonDIConsume, Class B inherits from A with additional SingletonDIConsume.
    /// Expected: Both classes have access to their declared dependencies
    /// </summary>
    [Fact]
    public void TC13_InheritanceChain_TwoLevelsWithConsumeAttribute_GeneratesCorrectProperties()
    {
        const string SOURCE = """
            using SingletonDI.Attributes;

            namespace MyApp.Services
            {
                [SingletonDIProvide]
                public class BaseService
                {
                    public void DoBaseWork() { }
                }

                [SingletonDIProvide]
                public class DerivedService
                {
                    public void DoDerivedWork() { }
                }

                // Base consumer with BaseService
                [SingletonDIConsume(typeof(BaseService))]
                public partial class ConsumerA
                {
                    public void UseBaseService()
                    {
                        BaseService service = BaseServiceInstance;
                        service.DoBaseWork();
                    }
                }

                // Derived consumer with additional DerivedService
                [SingletonDIConsume(typeof(DerivedService))]
                public partial class ConsumerB : ConsumerA
                {
                    public void UseBothServices()
                    {
                        BaseService baseService = BaseServiceInstance;
                        DerivedService derivedService = DerivedServiceInstance;
                        baseService.DoBaseWork();
                        derivedService.DoDerivedWork();
                    }
                }
            }
            """;

        var compilationErrors = CompilationErrors(SOURCE);

        Assert.Empty(compilationErrors);
    }

    /// <summary>
    /// TC14: Three-level inheritance chain with SingletonDIConsume at each level.
    /// Expected: All levels have access to their declared dependencies
    /// </summary>
    [Fact]
    public void TC14_InheritanceChain_ThreeLevelsWithConsumeAttribute_GeneratesCorrectProperties()
    {
        const string SOURCE = """
            using SingletonDI.Attributes;

            namespace MyApp.Services
            {
                [SingletonDIProvide]
                public class ServiceA
                {
                    public void DoWorkA() { }
                }

                [SingletonDIProvide]
                public class ServiceB
                {
                    public void DoWorkB() { }
                }

                [SingletonDIProvide]
                public class ServiceC
                {
                    public void DoWorkC() { }
                }

                // Level 1: ConsumerA consumes ServiceA
                [SingletonDIConsume(typeof(ServiceA))]
                public partial class ConsumerA
                {
                    public void UseServiceA()
                    {
                        ServiceA service = ServiceAInstance;
                        service.DoWorkA();
                    }
                }

                // Level 2: ConsumerB inherits from ConsumerA and consumes ServiceB
                [SingletonDIConsume(typeof(ServiceB))]
                public partial class ConsumerB : ConsumerA
                {
                    public void UseServicesAandB()
                    {
                        ServiceA serviceA = ServiceAInstance;
                        ServiceB serviceB = ServiceBInstance;
                        serviceA.DoWorkA();
                        serviceB.DoWorkB();
                    }
                }

                // Level 3: ConsumerC inherits from ConsumerB and consumes ServiceC
                [SingletonDIConsume(typeof(ServiceC))]
                public partial class ConsumerC : ConsumerB
                {
                    public void UseAllServices()
                    {
                        ServiceA serviceA = ServiceAInstance;
                        ServiceB serviceB = ServiceBInstance;
                        ServiceC serviceC = ServiceCInstance;
                        serviceA.DoWorkA();
                        serviceB.DoWorkB();
                        serviceC.DoWorkC();
                    }
                }
            }
            """;

        var compilationErrors = CompilationErrors(SOURCE);

        Assert.Empty(compilationErrors);
    }

    /// <summary>
    /// TC15: Inheritance chain with conflicting provider names at different levels.
    /// Expected: Namespaced properties are correctly generated for all levels
    /// </summary>
    [Fact]
    public void TC15_InheritanceChain_WithConflictingNames_GeneratesNamespacedProperties()
    {
        const string SOURCE = """
            using SingletonDI.Attributes;

            namespace NamespaceA
            {
                [SingletonDIProvide]
                public class Service { }
            }

            namespace NamespaceB
            {
                [SingletonDIProvide]
                public class Service { }
            }

            namespace NamespaceC
            {
                [SingletonDIProvide]
                public class Service { }
            }

            namespace ConsumerNamespace
            {
                // Level 1: ConsumerA consumes NamespaceA.Service
                [SingletonDIConsume(typeof(NamespaceA.Service))]
                public partial class ConsumerA
                {
                    public void UseServiceA()
                    {
                        NamespaceA.Service service = NamespaceA_ServiceInstance;
                    }
                }

                // Level 2: ConsumerB inherits from ConsumerA and adds NamespaceB.Service
                [SingletonDIConsume(typeof(NamespaceB.Service))]
                public partial class ConsumerB : ConsumerA
                {
                    public void UseServicesAandB()
                    {
                        NamespaceA.Service serviceA = NamespaceA_ServiceInstance;
                        NamespaceB.Service serviceB = NamespaceB_ServiceInstance;
                    }
                }

                // Level 3: ConsumerC inherits from ConsumerB and adds NamespaceC.Service
                [SingletonDIConsume(typeof(NamespaceC.Service))]
                public partial class ConsumerC : ConsumerB
                {
                    public void UseAllServices()
                    {
                        NamespaceA.Service serviceA = NamespaceA_ServiceInstance;
                        NamespaceB.Service serviceB = NamespaceB_ServiceInstance;
                        NamespaceC.Service serviceC = NamespaceC_ServiceInstance;
                    }
                }
            }
            """;

        var compilationErrors = CompilationErrors(SOURCE);

        Assert.Empty(compilationErrors);
    }

    /// <summary>
    /// TC16: Inheritance chain where derived class does NOT have SingletonDIConsume.
    /// Expected: Derived class can still access base class properties through inheritance
    /// </summary>
    [Fact]
    public void TC16_InheritanceChain_DerivedWithoutConsumeAttribute_AccessesBaseProperties()
    {
        const string SOURCE = """
            using SingletonDI.Attributes;

            namespace MyApp.Services
            {
                [SingletonDIProvide]
                public class MyService
                {
                    public void DoWork() { }
                }

                // Base consumer with SingletonDIConsume
                [SingletonDIConsume(typeof(MyService))]
                public partial class ConsumerBase
                {
                    public void UseService()
                    {
                        MyService service = MyServiceInstance;
                        service.DoWork();
                    }
                }

                // Derived consumer WITHOUT SingletonDIConsume - inherits property from base
                public class ConsumerDerived : ConsumerBase
                {
                    public void UseServiceFromDerived()
                    {
                        // Access the generated property from base class
                        MyService service = MyServiceInstance;
                        service.DoWork();
                    }
                }
            }
            """;

        var compilationErrors = CompilationErrors(SOURCE);

        Assert.Empty(compilationErrors);
    }

    /// <summary>
    /// TC17: Inheritance chain with custom property names at different levels.
    /// Expected: Custom names are preserved across inheritance chain
    /// </summary>
    [Fact]
    public void TC17_InheritanceChain_WithCustomNames_GeneratesCorrectProperties()
    {
        const string SOURCE = """
            using SingletonDI.Attributes;

            namespace MyApp.Services
            {
                [SingletonDIProvide("PrimaryDatabase")]
                public class DatabaseService
                {
                    public void ExecuteQuery() { }
                }

                [SingletonDIProvide("CacheStore")]
                public class CacheService
                {
                    public void GetCachedData() { }
                }

                [SingletonDIProvide("Logger")]
                public class LoggingService
                {
                    public void Log() { }
                }

                // Level 1: ConsumerA uses DatabaseService with custom name
                [SingletonDIConsume(typeof(DatabaseService))]
                public partial class ConsumerA
                {
                    public void UseDatabase()
                    {
                        DatabaseService db = PrimaryDatabase;
                        db.ExecuteQuery();
                    }
                }

                // Level 2: ConsumerB adds CacheService with custom name
                [SingletonDIConsume(typeof(CacheService))]
                public partial class ConsumerB : ConsumerA
                {
                    public void UseDatabaseAndCache()
                    {
                        DatabaseService db = PrimaryDatabase;
                        CacheService cache = CacheStore;
                        db.ExecuteQuery();
                        cache.GetCachedData();
                    }
                }

                // Level 3: ConsumerC adds LoggingService with custom name
                [SingletonDIConsume(typeof(LoggingService))]
                public partial class ConsumerC : ConsumerB
                {
                    public void UseAllServices()
                    {
                        DatabaseService db = PrimaryDatabase;
                        CacheService cache = CacheStore;
                        LoggingService logger = Logger;
                        db.ExecuteQuery();
                        cache.GetCachedData();
                        logger.Log();
                    }
                }
            }
            """;

        var compilationErrors = CompilationErrors(SOURCE);

        Assert.Empty(compilationErrors);
    }

    #endregion

    #region Helper Methods

    /// <summary>
    /// Asserts that the source code compiles successfully after running the generator.
    /// </summary>
    private static List<Diagnostic> CompilationErrors(string source)
    {
        var compilation = CreateCompilation(source);
        var generator = new SingletonDIGenerator();
        var driver = CSharpGeneratorDriver.Create(generator);

        driver.RunGeneratorsAndUpdateCompilation(compilation, out var outputCompilation, out var generatorDiagnostics);

        // Check for generator errors
        var generatorErrors = generatorDiagnostics.Where(d => d.Severity == DiagnosticSeverity.Error).ToList();
        Assert.Empty(generatorErrors);

        var compilationErrors = outputCompilation.GetDiagnostics()
            .Where(d => d.Severity == DiagnosticSeverity.Error)
            .ToList();

        return compilationErrors;
    }

    private static CSharpCompilation CreateCompilation(string source)
    {
        var references = new List<MetadataReference>
        {
            MetadataReference.CreateFromFile(typeof(object).Assembly.Location),
            MetadataReference.CreateFromFile(typeof(Task).Assembly.Location),
            MetadataReference.CreateFromFile(typeof(Attributes.SingletonDIProvideAttribute).Assembly.Location),
        };

        // Add all referenced assemblies
        var assemblyPath = Path.GetDirectoryName(typeof(object).Assembly.Location)!;
        foreach (var assemblyName in new[] { "System.Runtime", "System.Collections", "System.Linq", "netstandard", "System.Console", "System.Runtime.InteropServices.RuntimeInformation" })
        {
            var path = Path.Combine(assemblyPath, assemblyName + ".dll");
            if (File.Exists(path))
            {
                references.Add(MetadataReference.CreateFromFile(path));
            }
        }

        return CSharpCompilation.Create(
            "TestAssembly",
            [CSharpSyntaxTree.ParseText(source)],
            references,
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));
    }

    #endregion
}
